# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7946b6956e08595108ee48fd694ae69faa506d4c9e737e9ca04ff7d673a9eb35e9c5e8515e058fb7231d97daa2acaffe52ccd5a81a460fb47cdff968cca6003a
  wepay_client_id: <%= ENV['bro_montana_social_club_wepay_staging_client_id'] %>
  wepay_client_secret: <%= ENV['bro_montana_social_club_wepay_staging_client_secret'] %>
  wepay_access_token: <%= ENV['bro_montana_social_club_wepay_staging_access_token'] %>
  wepay_account_id: <%= ENV['bro_montana_social_club_wepay_staging_account_id'] %>

test:
  secret_key_base: 6cae2d4969a052cc41e5abdebc875f3d3551a98a2a55dd4024957bb63f6cccd4041d639cc744c6d1f0dd3817cf90c40c4430077f44b41207c3ca3156926317ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
